#!/usr/bin/env bash
# Push the DAGs, the dbt project and the rendered runtime configuration into the
# VM, then initialise Airflow's metadata database.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
# shellcheck source=lib.sh
source ./lib.sh

require_cmd docker
require_env VM_CONTAINER PROJECT_ID DATASET_RAW DATASET_STAGING DATASET_MARTS \
            BUCKET_RAW BUCKET_CURATED BUCKET_ARTIFACTS PUBSUB_TOPIC

[[ "$(container_state "$VM_CONTAINER")" == "running" ]] \
  || die "VM container '${VM_CONTAINER}' is not running"

GUEST_ENDPOINT="$(guest_endpoint "$VM_CONTAINER" "${MINISKY_PORT:-8080}")"
# Paths are resolved relative to this script, not to terraform's working directory.
SRC="../pipeline"

log "deploying pipeline code to ${VM_CONTAINER}"

docker exec "$VM_CONTAINER" mkdir -p \
  /opt/pipeline/dags /opt/pipeline/lib /opt/pipeline/dbt /opt/pipeline/airflow /opt/pipeline/logs

docker cp "${SRC}/dags/." "${VM_CONTAINER}:/opt/pipeline/dags/"
docker cp "${SRC}/lib/."  "${VM_CONTAINER}:/opt/pipeline/lib/"
docker cp "${SRC}/dbt/."  "${VM_CONTAINER}:/opt/pipeline/dbt/"
ok "code copied"

# ── Runtime configuration ────────────────────────────────────────────────────
# One file is the single source of truth for both Airflow and dbt inside the VM.
ENV_FILE="$(mktemp)"
trap 'rm -f "$ENV_FILE"' EXIT
cat > "$ENV_FILE" <<ENVEOF
# Generated by terraform (deploy_pipeline.sh) — do not edit by hand.
export PIPELINE_HOME=/opt/pipeline

# MiniSky (reached over the VPC's Docker gateway; 'localhost' is the VM itself)
export MINISKY_ENDPOINT=${GUEST_ENDPOINT}
export MINISKY_PROJECT=${PROJECT_ID}
export GOOGLE_CLOUD_PROJECT=${PROJECT_ID}
export MINISKY_ACCESS_TOKEN=${MINISKY_ACCESS_TOKEN:-minisky-local-token}

# Warehouse / lake / eventing
export BQ_DATASET_RAW=${DATASET_RAW}
export BQ_DATASET_STAGING=${DATASET_STAGING}
export BQ_DATASET_MARTS=${DATASET_MARTS}
export BUCKET_RAW=${BUCKET_RAW}
export BUCKET_CURATED=${BUCKET_CURATED}
export BUCKET_ARTIFACTS=${BUCKET_ARTIFACTS}
export PUBSUB_TOPIC=${PUBSUB_TOPIC}

# Airflow
export AIRFLOW_HOME=/opt/pipeline/airflow
export AIRFLOW__CORE__DAGS_FOLDER=/opt/pipeline/dags
export AIRFLOW__CORE__LOAD_EXAMPLES=False
export AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
export AIRFLOW__WEBSERVER__WEB_SERVER_PORT=${AIRFLOW_PORT:-8080}
export AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
export AIRFLOW__LOGGING__BASE_LOG_FOLDER=/opt/pipeline/airflow/logs

# dbt
export DBT_PROFILES_DIR=/opt/pipeline/dbt
export DBT_PROJECT_DIR=/opt/pipeline/dbt/analytics
export DBT_BIN=/opt/pipeline/dbt-venv/bin/dbt

# Trino
export TRINO_PORT=${TRINO_PORT:-8090}
export TRINO_SERVER=http://localhost:${TRINO_PORT:-8090}

export PYTHONPATH=/opt/pipeline/lib
export PATH=/opt/pipeline/venv/bin:/root/.local/bin:\$PATH
ENVEOF

docker cp "$ENV_FILE" "${VM_CONTAINER}:/opt/pipeline/env.sh"
docker exec "$VM_CONTAINER" chmod 0644 /opt/pipeline/env.sh
ok "runtime config written to /opt/pipeline/env.sh"

# A host-side copy so the operator scripts can run without terraform's environment.
cat > ../.pipeline.env <<HOSTEOF
VM_CONTAINER=${VM_CONTAINER}
VM_NAME=${VM_NAME:-}
ZONE=${ZONE:-us-central1-a}
PROJECT_ID=${PROJECT_ID}
MINISKY_ENDPOINT=${MINISKY_ENDPOINT:-http://localhost:8080}
MINISKY_GUEST_ENDPOINT=${GUEST_ENDPOINT}
NAME_PREFIX=${NAME_PREFIX:-retail}
DATASET_RAW=${DATASET_RAW}
DATASET_STAGING=${DATASET_STAGING}
DATASET_MARTS=${DATASET_MARTS}
BUCKET_RAW=${BUCKET_RAW}
BUCKET_CURATED=${BUCKET_CURATED}
BUCKET_ARTIFACTS=${BUCKET_ARTIFACTS}
PUBSUB_TOPIC=${PUBSUB_TOPIC}
AIRFLOW_PORT=${AIRFLOW_PORT:-8080}
TRINO_PORT=${TRINO_PORT:-8090}
HOSTEOF
ok "host-side env written to .pipeline.env"

# ── Airflow metadata database ────────────────────────────────────────────────
log "initialising the Airflow metadata database"
vm_exec_env "$VM_CONTAINER" /opt/pipeline/env.sh \
  '/opt/pipeline/venv/bin/airflow db migrate' >/dev/null
ok "Airflow database ready"

# A deterministic local login beats a generated password for an emulator stack.
vm_exec_env "$VM_CONTAINER" /opt/pipeline/env.sh \
  '/opt/pipeline/venv/bin/airflow users create \
     --username admin --password admin --firstname Local --lastname Admin \
     --role Admin --email admin@minisky.local' >/dev/null 2>&1 \
  && ok "Airflow admin user created (admin / admin)" \
  || log "Airflow admin user already present"

# ── dbt sanity check ─────────────────────────────────────────────────────────
log "validating the dbt project"
if vm_exec_env "$VM_CONTAINER" /opt/pipeline/env.sh \
     'cd $DBT_PROJECT_DIR && $DBT_BIN parse --profiles-dir $DBT_PROFILES_DIR' >/dev/null 2>&1; then
  ok "dbt project parses"
else
  warn "dbt parse reported problems — run scripts/pipeline_status.sh for detail"
fi

ok "pipeline deployed"
